FROM debian:11

RUN apt-get -q update && apt-get install --no-install-recommends -yq \
  linux-image-amd64 \
  libguestfs-tools \
  syslinux \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /guestfs-appliance
RUN libguestfs-make-fixed-appliance /guestfs-appliance
ENV LIBGUESTFS_PATH=/guestfs-appliance
